wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import os

import flask.helpers
from flask import Blueprint, abort
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import send_file
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from wiki.core import Processor
from wiki.web.downloads import generatePDF, generateTXT
from wiki.web.forms import EditorForm, RegisterForm, UnregisterForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki, current_profiles
from wiki.web import current_users
from wiki.web.profile import Profile
from wiki.web.user import protect

bp = Blueprint('wiki', __name__)

@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')

@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)

@bp.route('/static/content/<path:image_name>')
@protect
def send_file(image_name):
    return current_wiki.get_image(image_name)

@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)


@bp.route('/<path:url>/pdf')
@protect
def topdf(url):
    page = current_wiki.get_or_404(url)
    html = render_template('pdf_and_txt_page.html', page=page)
    pdf_file_path = f"{os.getcwd()}/{url}.pdf"
    print(pdf_file_path)
    generatePDF(pdf_file_path, html)
    return flask.helpers.send_file(pdf_file_path, as_attachment=True)


@bp.route('/<path:url>/txt')
@protect
def totxt(url):
    page = current_wiki.get_or_404(url)
    html = render_template('pdf_and_txt_page.html', page=page)
    txt_file_path = f"{os.getcwd()}/{url}.txt"
    print(txt_file_path)
    generateTXT(txt_file_path, html)
    return flask.helpers.send_file(txt_file_path, as_attachment=True)

@bp.route('/image/<path:page_number>', methods=['GET', 'POST'])
@protect
def image(page_number):
    return render_template('images.html',
        current_page = int(page_number[1:]) ,
        gallery = current_wiki.get_gallery_page(page_number[1:]),
        final_page = len(current_wiki.get_gallery()) // 6 + 1,
        des = current_wiki.get_image_des())

@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)

@bp.route('/upload', methods=["GET", "POST"])
@protect
def upload():
    if request.method == "POST":
        image = request.files["image"]
        description = request.form.get("description")

        if image and description and image.filename.split(".")[-1].lower() in ["png", "jpg", "jpeg", "gif"]:
            if (current_wiki.img_exists(image.filename)):
                flash("Image already exist!", "danger")
            else:
                current_wiki.save_image(image, description)
                flash("Successfully uploaded image to gallery!", "success")
            return redirect(url_for("wiki.upload"))
        else:
            flash("An error occurred while uploading the image!", "danger")
            return redirect(url_for("wiki.upload"))
    return render_template("upload.html")

@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/register/', methods=['GET', 'POST'])
def user_register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = current_users.add_user(form.username.data, form.password.data)
        current_profiles.add_profile(Profile(form.username.data, form.full_name.data, form.bio.data))
        login_user(user)
        user.set('authenticated', True)
        flash('Registration successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('register.html', form=form)


@bp.route('/user/unregister/', methods=['GET', 'POST'])
@protect
def user_unregister():
    form = UnregisterForm()
    if form.validate_on_submit():
        username = current_user.get_id()
        current_user.set('authenticated', False)
        current_users.delete_user(username)
        current_profiles.delete_profile(username)
        logout_user()
        flash(f"Account {username} deleted", 'success')
        return redirect(url_for('wiki.user_login'))
    return render_template('unregister.html', form=form)


@bp.route('/user/<username>', methods=['GET', 'POST'])
@protect
def user_profile(username):
    profile = current_profiles.get_profile(username)
    if not profile:
        profile = abort(404)
    return render_template('profile.html', profile=profile)


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    pass


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand">{{ config.TITLE }}</a>
							<ul class="nav">
								<li><a href="{{ url_for('wiki.home') }}">Home</a></li>
								<li><a href="{{ url_for('wiki.index') }}">Index</a></li>
								<li><a href="{{ url_for('wiki.tags') }}">Tags</a></li>
								<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
								<li><a href="{{ url_for('wiki.image', page_number = '_1') }}">Images</a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
								{% if current_user.is_anonymous %}
									<li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
								{% else %}
                                    <div class="dropdown">
                                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{ current_user.get_id() }}
                                        <svg width="1em" height="0.5em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                          <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item" href="{{ url_for('wiki.user_profile', username=current_user.get_id()) }}">Profile</a>
                                            <a class="dropdown-item" href="{{ url_for('wiki.user_logout') }}">Logout</a>
                                            <a class="dropdown-item" href="{{ url_for('wiki.user_unregister') }}">Unregister</a>
                                        </div>
                                    </div>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/editor.html
{% extends "base.html" %}

{% block title -%}
Wiki Editor
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
	<li class="active"><a href="#editor" data-toggle="tab">Editor</a></li>
	<li><a href="#preview" data-toggle="tab" id="previewlink">Preview</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="editor">
		<form method="post" class="form">
			{{ form.hidden_tag() }}
			{{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
			{{ input(form.body, placeholder="Markdown", class="span7", rows="20") }}
			{{ input(form.tags, placeholder="Tags (comma separated)", class="span7", autocomplete="off") }}
			<div class="form-actions">
        <div class="pull-left">
          <a class="btn" href="#preview" id="previewbtn">Preview</a>
        </div>
				<div class="pull-right">
          <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
					<button class="btn btn-success" type="submit">Save</button>
				</div>
			</div>
		</form>
	</div>
	<div class="tab-pane" id="preview"></div>
</div>
{% endblock content %}

{% block sidebar %}
<h3>Editor How-To</h3>
<p>This editor is <a href="http://daringfireball.net/projects/markdown/">markdown</a> featured.</p>
<pre><code>* I
* am
* a
* list</code></pre>
Turns into:
<ul>
<li>I</li>
<li>am</li>
<li>a</li>
<li>list</li>
</ul>
<p><code>**bold** and *italics*</code> turn into <strong>bold</strong> and <em>italics</em>. Very easy!</p>
<p>Create links with <code>[NoTube](http://www.notube.com)</code>. They turn into <a href="http://www.notube.com">NoTube</a>.</p>
<p>Headers are as follows:</p>
<pre><code># Level 1
## Level 2
### Level 3</code></pre>
<p></p>

{% endblock sidebar %}

{% block postscripts -%}
{{ super() }}
$('#previewlink').on('click', function() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $inputs.prop('disabled', true);
  $pre.removeClass('alert').removeClass('alert-error').html("Loading...");
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
      console.log(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('There was a problem with the preview.');
    },
    complete: function() {
      $inputs.prop('disabled', false);
    }
  });
});
$('#previewbtn').on('click', function(event) {
	event.preventDefault();
	$('#previewlink').click();
});
{%- endblock postscripts %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

{% macro render_field(field) %}
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
    <ul class="text-error">
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
    </ul>
        {% endif %}
    </dd>
{% endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/images.html
{% extends "base.html" %}
{% block title -%}
  Gallery
{%- endblock title %}
{% block content %}
  <div class="container">
    <a href="{{ url_for('wiki.upload') }}" class="btn btn-success" >Upload Images</a>
    
    {% for row in range((gallery|length - 1)//3 + 1) %}
      <div class = "row">
        {% for i in range(0, 3) %}
          {% if i + row * 3 < gallery|length%}
            <div class="span4">
              <div class="card">
                <img src="{{ url_for('static', filename = 'content/' + gallery[i+row*3]) }}" class="card-img-top">
                <div class="card-body">
                  <a href="{{ url_for('static', filename = 'content/' + gallery[i+row*3]) }}">
                    <h5 class="card-title">{{gallery[i+row*3]}}</h5>
                  </a>
                  <p class="card-text">{{ des[gallery[i+row*3]]["description"] }}</p>
                </div>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      </div>
    {% endfor %}

    <ul class="pager">
      <li><a href="{{ url_for('wiki.image', page_number = '_1') }}"><<</a></li>

      {% if current_page - 1 <= 0 %}
        <li><a href="{{ url_for('wiki.image', page_number = '_1') }}"><</a></li>
      {% else %}
        <li><a href="{{ url_for('wiki.image', page_number = '_' + (current_page - 1)|string) }}"><</a></li>
      {% endif %}



      {% if current_page + 1 >= final_page %}
        <li><a href="{{ url_for('wiki.image', page_number = '_' + final_page|string) }}">></a></li>
      {% else %}
        <li><a href="{{ url_for('wiki.image', page_number = '_' + (current_page + 1)|string) }}">></a></li>
      {% endif %}

      <li><a href="{{ url_for('wiki.image', page_number = '_' + final_page|string) }}">>></a></li>
    </ul>
  </div>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
	{{ page.title }}
{% endblock title %}

{% block content %}
  <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
      <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
      <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
    </div>
  </div>
	{{ page }}
{% endblock content %}

{% block sidebar %}
<h6> Last edited on: <i>{{page.date}}</i></h6>
{% if page.tags %}
<h3>Tags</h3>
  <ul>
      {% for tag in page.tags.split(',') %}
        <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}
<h3>Actions</h3>
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
  <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
  <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>
  <li><a href="{{ url_for('wiki.topdf', url=page.url) }}">Download PDF</a></li>
  <li><a href="{{ url_for('wiki.totxt', url=page.url) }}">Download TXT</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/pdf_and_txt_page.html
<h1>{{ page.title }}</h1>

<br>

{{ page }}

<br>

{% if page.tags %}
<h3>Tags</h3>
<ul>
  {% for tag in page.tags.split(',') %}
    <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
  {% endfor %}
</ul>
{% endif %}

wiki/web/templates/profile.html
{% extends "base.html" %}

{% block title %}
	{{ profile.full_name }} <h4 style="color: grey">{{ profile.username }}</h4>
{% endblock title %}

{% block content %}
    <div style="word-wrap: break-word">
        {{ profile.bio }}
    </div>
{% endblock content %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/unregister.html
{% extends "base.html" %}
{% from "helpers.html" import render_field %}

{% block title %}Unregister{% endblock title %}

{% block content %}
    This action cannot be undone.
    This will permanently delete the {{ current_user.get_id() }} account and profile.
    <form method="POST">
        {{ form.hidden_tag() }}
        Please type <b>{{ current_user.get_id() }}</b> to confirm {{ render_field(form.username) }}
        <input type="submit" class="btn btn-danger" value="Unregister">
    </form>
{% endblock content %}